-- MySQL Script generated by MySQL Workbench
-- Sat May 10 11:47:40 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema metro
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema metro
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `metro` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `metro` ;

-- -----------------------------------------------------
-- Table `metro`.`station`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `metro`.`station` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` TEXT NOT NULL,
  `line` TEXT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `metro`.`employee`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `metro`.`employee` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `id_station` INT NOT NULL,
  `name` VARCHAR(45) NULL DEFAULT NULL,
  `surname` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `id_station` (`id_station` ASC) VISIBLE,
  CONSTRAINT `employee_ibfk_1`
    FOREIGN KEY (`id_station`)
    REFERENCES `metro`.`station` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `metro`.`employment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `metro`.`employment` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `id_employee` INT NOT NULL,
  `date` DATE NOT NULL,
  `current_statemants` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `id_employee` (`id_employee` ASC) VISIBLE,
  CONSTRAINT `employment_ibfk_1`
    FOREIGN KEY (`id_employee`)
    REFERENCES `metro`.`employee` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `metro`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `metro`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `password` TEXT NOT NULL,
  `email` TEXT NOT NULL,
  `firstname` VARCHAR(20) NOT NULL DEFAULT 'Имя',
  `lastname` VARCHAR(20) NOT NULL DEFAULT 'Фамилия',
  `mobility` TEXT NOT NULL,
  `role` ENUM('user', 'admin') NOT NULL DEFAULT 'user',
  PRIMARY KEY (`id`),
  INDEX `role_idx` (`role` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `metro`.`statemants`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `metro`.`statemants` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `bagage` TEXT NOT NULL,
  `date` DATE NOT NULL,
  `status` TEXT NOT NULL,
  `id_station_start` INT NOT NULL,
  `id_station_end` INT NOT NULL,
  `id_user` INT NOT NULL,
  `id_employee` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `id_employee` (`id_employee` ASC) VISIBLE,
  INDEX `id_station_start` (`id_station_start` ASC) VISIBLE,
  INDEX `id_station_end` (`id_station_end` ASC) VISIBLE,
  INDEX `id_user` (`id_user` ASC) VISIBLE,
  CONSTRAINT `fk_statemants_employee`
    FOREIGN KEY (`id_employee`)
    REFERENCES `metro`.`employee` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_statemants_station_end`
    FOREIGN KEY (`id_station_end`)
    REFERENCES `metro`.`station` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_statemants_station_start`
    FOREIGN KEY (`id_station_start`)
    REFERENCES `metro`.`station` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_statemants_user`
    FOREIGN KEY (`id_user`)
    REFERENCES `metro`.`users` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `metro`.`statement_employees`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `metro`.`statement_employees` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `statement_id` INT NOT NULL,
  `employee_id` INT NOT NULL,
  `is_main` TINYINT NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  INDEX `statement_id` (`statement_id` ASC) VISIBLE,
  INDEX `employee_id` (`employee_id` ASC) VISIBLE,
  CONSTRAINT `statement_employees_ibfk_1`
    FOREIGN KEY (`statement_id`)
    REFERENCES `metro`.`statemants` (`id`)
    ON DELETE CASCADE,
  CONSTRAINT `statement_employees_ibfk_2`
    FOREIGN KEY (`employee_id`)
    REFERENCES `metro`.`employee` (`id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
